services:
  bv_app:
    build: .
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./static/generated:/app/static/generated
